# Generated by Django 3.2 on 2021-04-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название активности')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('is_parent', models.BooleanField(default=False, verbose_name='Является родителем')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='main.activities', verbose_name='Родитель')),
            ],
        ),
    ]
