# Generated by Django 3.2 on 2021-04-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activities_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер ребенка'),
        ),
    ]
