# Generated by Django 3.2 on 2021-04-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_activities_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет'),
        ),
    ]
