# Generated by Django 3.2 on 2021-04-27 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_activities_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('status', models.CharField(choices=[('P', 'В процессе'), ('F', 'Завершено')], default='P', max_length=1, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('finished', models.DateTimeField(verbose_name='Закончен')),
                ('activity', models.ForeignKey(default=main.models.Activities(1, 'Полезные', '#14AA04', None, True, 1, 1), on_delete=django.db.models.deletion.CASCADE, to='main.activities', verbose_name='Вид деятельности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
