# Generated by Django 3.2 on 2021-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закончен'),
        ),
    ]
