# Generated by Django 3.2 on 2021-04-28 15:54

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_projects_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='activity',
            field=models.ForeignKey(blank=True, default=main.models.Activities(1, 'Полезные', '#14AA04', None, True, 1, 1), null=True, on_delete=django.db.models.deletion.CASCADE, to='main.activities', verbose_name='Вид деятельности'),
        ),
    ]
