# Generated by Django 3.2 on 2021-04-30 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210430_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Потрачено времени'),
        ),
    ]
