# Generated by Django 3.2 on 2021-04-30 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_activities_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.activities', verbose_name='Вид деятельности'),
        ),
    ]
