# Generated by Django 3.2 on 2021-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210505_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-date', '-start'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='projects',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет'),
        ),
    ]
